theme: jekyll-theme-cayman

github:
  private: false
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/PineappleIndustries/pineappleindustries.github.io"
  
title: My Webpage Home Page
description: This is meant to provide information to those interested on my internet activities and presence.
