theme: jekyll-theme-primer

github:
  private: false
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/PineappleIndustries/pineappleindustries.github.io"
  
title: ![Icon](https://i.imgur.com/tXBvVOe.png)
description: This is meant to be a project of my interests and of no important purpose to provide a website or webpage for myself.
